// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqdkzxnxkcsqwynsbthb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZGt6eG54a2NzcXd5bnNidGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNDg2NjgsImV4cCI6MjA1MjcyNDY2OH0.bGkE_j5Nu7SxcIC-AmkYP3jEhJqAdJawKXf4ZgUavZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);